use crate::error::Result;
use std::fs;
use std::path::Path;

pub fn generate(project_root: &Path, output_dir: &str) -> Result<()> {
    let output_path = project_root.join(output_dir);
    fs::create_dir_all(&output_path)?;

    // Generate package.json
    let package_json = r#"{
  "name": "suiforge-sdk",
  "version": "0.1.0",
  "description": "Auto-generated TypeScript SDK for Sui smart contracts",
  "main": "dist/index.js",
  "types": "dist/index.d.ts",
  "scripts": {
    "build": "tsc",
    "test": "jest"
  },
  "dependencies": {
    "@mysten/sui.js": "^0.50.0"
  },
  "devDependencies": {
    "@types/node": "^20.0.0",
    "typescript": "^5.0.0"
  }
}
"#;
    fs::write(output_path.join("package.json"), package_json)?;

    // Generate tsconfig.json
    let tsconfig = r#"{
  "compilerOptions": {
    "target": "ES2020",
    "module": "commonjs",
    "declaration": true,
    "outDir": "./dist",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules", "dist"]
}
"#;
    fs::write(output_path.join("tsconfig.json"), tsconfig)?;

    // Create src directory
    let src_path = output_path.join("src");
    fs::create_dir_all(&src_path)?;

    // Generate index.ts
    let index_ts = r#"import { TransactionBlock } from '@mysten/sui.js/transactions';
import { SuiClient } from '@mysten/sui.js/client';

export class SuiForgeClient {
  private client: SuiClient;
  private packageId: string;

  constructor(client: SuiClient, packageId: string) {
    this.client = client;
    this.packageId = packageId;
  }

  /**
   * Get the package ID
   */
  getPackageId(): string {
    return this.packageId;
  }

  /**
   * Create a new transaction block
   */
  createTransaction(): TransactionBlock {
    return new TransactionBlock();
  }

  // Auto-generated methods will be added here based on Move modules
}

export * from './types';
"#;
    fs::write(src_path.join("index.ts"), index_ts)?;

    // Generate types.ts
    let types_ts = r#"/**
 * Auto-generated TypeScript types for Sui smart contracts
 */

export interface TransactionResult {
  digest: string;
  effects: any;
}

export interface ObjectRef {
  objectId: string;
  version: string;
  digest: string;
}

// Additional types will be generated based on Move structs
"#;
    fs::write(src_path.join("types.ts"), types_ts)?;

    // Generate README
    let readme = r#"# SuiForge TypeScript SDK

Auto-generated TypeScript SDK for interacting with your Sui smart contracts.

## Installation

```bash
npm install
npm run build
```

## Usage

```typescript
import { SuiClient } from '@mysten/sui.js/client';
import { SuiForgeClient } from './src';

const client = new SuiClient({ url: 'https://fullnode.devnet.sui.io:443' });
const packageId = '0x...'; // Your deployed package ID

const suiforge = new SuiForgeClient(client, packageId);

// Use the generated methods
const tx = suiforge.createTransaction();
// ... add transaction commands
```

## Development

This SDK is auto-generated by SuiForge. To regenerate:

```bash
suiforge generate ts
```
"#;
    fs::write(output_path.join("README.md"), readme)?;

    Ok(())
}
